# Generated by Django 5.1.3 on 2024-11-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0001_initial'),
    ]

    operations = [
    ]
